# Site settings
title: Life Thoughts / Uriel Ofir
description: A public journal containing my personal thoughts and lessons learned about life, well-being, and personal growth.
baseurl: "" # Change this to empty
url: "https://urielofir.github.io" # Remove /life-thoughts

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages safe plugins
safe: true
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .bundle/